site_name: impulsar docs
site_url: https://aimotrens.github.io/impulsar/

nav:
  - Home: index.md
  - Installation: installation/install.md
  - Features:
    - Overview: features/overview.md
    - Script: features/script.md
    - Shell: features/shell.md
    - If: features/if.md
    - Conditional: features/conditional.md
    - AllowFail: features/allow_fail.md
    - WorkDir: features/work_dir.md
    - Variables: features/variables.md
    - Arguments: features/arguments.md
    - Foreach: features/foreach.md
    - Dependencies: features/dependencies.md
    - Finalizers: features/finalizers.md


theme:
  name: material
  language: en
  font: false
  features:
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css: 
  - assets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - markdownextradata
